// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlbyxwrfjtoopuduylop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sYnl4d3JmanRvb3B1ZHV5bG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM5OTEsImV4cCI6MjA2NTU3OTk5MX0.ypys_3K3Sx5lX3kg_Hrz_oCJq7vvxhjafuTeQHiD1ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);